# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение датчиков
GET {{baseUrl}}/sensors/
Content-Type: application/json

###

# создание датчика
POST {{baseUrl}}/sensors/
Content-Type: application/json

{
  "name": "32",
  "description": "Датчик"
}

###

# обновление датчика
PATCH {{baseUrl}}/sensors/4/
Content-Type: application/json

{
  "name": "54"
}

###

# добавление измерения
POST {{baseUrl}}/measurements/
Content-Type: application/json

{
  "sensor": 4,
  "temperature": 20.3
}

###

# получение информации по датчику
GET {{baseUrl}}/sensors/3/
Content-Type: application/json

###

# получение измерений
GET {{baseUrl}}/measurements/
Content-Type: application/json
