# примеры API-запросов

@baseUrl = http://localhost:8000/api/v1

# создание продукта
POST {{baseUrl}}/products/
Content-Type: application/json

{
  "title": "Баклажаны",
  "description": "Лучшие баклажаны"
}

###

# получение продуктов
GET {{baseUrl}}/products/
Content-Type: application/json

###

# обновление продукта
PATCH {{baseUrl}}/products/2/
Content-Type: application/json

{
  "description": "Самые ароматные помидорки"
}

###

# удаление продукта
DELETE {{baseUrl}}/products/3/
Content-Type: application/json

###

# поиск продуктов по названию и описанию
GET {{baseUrl}}/products/?search=баклаж
Content-Type: application/json

###

# создание склада
POST {{baseUrl}}/stocks/
Content-Type: application/json

{
  "address": "Климова, 8",
  "positions": [
    {
      "product": 1,
      "quantity": 250,
      "price": 120.50
    },
    {
      "product": 4,
      "quantity": 100,
      "price": 180
    }
  ]
}

###

# обновляем записи на складе
PATCH {{baseUrl}}/stocks/1/
Content-Type: application/json

{
  "positions": [
    {
      "product": 5,
      "quantity": 120,
      "price": 130.70
    },
    {
      "product": 2,
      "quantity": 223,
      "price": 143
    }
  ]
}

###

# поиск складов, где есть определенный продукт,
# по идентификатору продукта
GET {{baseUrl}}/stocks/?products__id=5
Content-Type: application/json


###

# поиск складов, где есть определенный продукт,
# по названию продукта, его части или части описания
GET {{baseUrl}}/stocks/?search=помид
Content-Type: application/json

###

# удалить информацию о складе
DELETE {{baseUrl}}/stocks/3/
Content-Type: application/json

###

# информация о складах
GET {{baseUrl}}/stocks/
Content-Type: application/json
